# Generated by Django 3.1.4 on 2022-09-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand'),
            preserve_default=False,
        ),
    ]
